'use client';
import { useEffect, useRef, useState, FormEvent } from 'react';
import { LayoutDashboard, Car, Bike, Truck, ArrowDownLeft, ArrowUpRight, Grid2X2, Receipt, SlidersHorizontal, MapPin, Users, ShieldCheck, BarChart3, Search, Bell, ChevronRight, ArrowRight, Plus, X, LogOut, RefreshCw, Download, Printer, Check, CircleParking, Menu, Loader2, Wallet, Clock3, Ticket, Settings, ScanLine } from 'lucide-react';
import QRCode from 'qrcode';
type Row = Record<string, any>;
let csrf = '';
async function api(path: string, method = 'GET', body?: Row, key?: string) {
 const res = await fetch('/api'+path, {method, credentials:'same-origin',headers:{Accept:'application/json','Content-Type':'application/json','X-CSRF-TOKEN':csrf,...(key?{'Idempotency-Key':key}:{})},...(body?{body:JSON.stringify(body)}:{})});
 const data = await res.json(); if(!res.ok) throw new Error(data.errors ? Object.values(data.errors).flat().join(' ') : data.message || 'Permintaan gagal.'); return data;
}
const money=(v:number)=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(v||0);
const date=(v:string)=>v?new Date(v.includes('T')?v:v.replace(' ','T')+'+07:00').toLocaleString('id-ID',{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'}):'—';
const types:Row={CAR:'Mobil',MOTORCYCLE:'Motor',TRUCK:'Truk',BUS:'Bus',OTHER:'Lainnya'};
const statuses:Row={AVAILABLE:'Tersedia',OCCUPIED:'Terisi',MAINTENANCE:'Perawatan',DISABLED:'Nonaktif',ACTIVE:'Aktif',COMPLETED:'Selesai',PAID:'Lunas'};
const nav=[['dashboard','Ringkasan',LayoutDashboard],['slots','Area & slot',Grid2X2],['sessions','Sesi parkir',Car],['payments','Transaksi',Receipt],['vehicles','Kendaraan',Truck],['reports','Laporan',BarChart3],['locations','Lokasi',MapPin],['rates','Tarif parkir',SlidersHorizontal],['staff','Petugas',Users],['audit','Audit aktivitas',ShieldCheck],['settings','Pengaturan',Settings]] as const;
const adminPages=['reports','locations','rates','staff','audit'];
function Badge({value}:{value:string}){return <span className={'badge '+value.toLowerCase()}><i/>{statuses[value]||value}</span>}
function TypeIcon({type,size=20}:{type:string,size?:number}){return type==='MOTORCYCLE'?<Bike size={size}/>:type==='CAR'?<Car size={size}/>:<Truck size={size}/>}
function Empty({text='Belum ada data untuk ditampilkan.'}:{text?:string}){return <div className="empty"><CircleParking size={36}/><strong>{text}</strong><span>Aktivitas parkir Anda akan muncul di sini.</span></div>}
function QR({token}:{token:string}){const [src,setSrc]=useState(''); useEffect(()=>{QRCode.toDataURL(window.location.origin+'/ticket/'+token,{width:240,margin:2,errorCorrectionLevel:'M'}).then(setSrc);},[token]); return src?<img className="qr" src={src} alt="QR tiket parkir"/>:<Loader2 className="spin"/>}
export default function Home(){
 const [user,setUser]=useState<Row|null>(null),[ready,setReady]=useState(false),[page,setPage]=useState('dashboard'),[data,setData]=useState<Row>({}),[dashboard,setDashboard]=useState<Row>({}),[slots,setSlots]=useState<Row[]>([]),[areas,setAreas]=useState<Row[]>([]),[locations,setLocations]=useState<Row[]>([]),[busy,setBusy]=useState(false),[loading,setLoading]=useState(false),[error,setError]=useState(''),[toast,setToast]=useState(''),[modal,setModal]=useState(''),[ticket,setTicket]=useState<Row|null>(null),[quote,setQuote]=useState<Row|null>(null),[query,setQuery]=useState(''),[lost,setLost]=useState(false),[areaFilter,setAreaFilter]=useState('all'),[statusFilter,setStatusFilter]=useState('all'),[search,setSearch]=useState(''),[mobile,setMobile]=useState(false),[pageNum,setPageNum]=useState(1),[type,setType]=useState('CAR'),[edit,setEdit]=useState<Row|null>(null),[from,setFrom]=useState(new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Jakarta'}).slice(0,7)+'-01'),[to,setTo]=useState(new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Jakarta'})),[notifications,setNotifications]=useState(false);
 const mutationKey=useRef(''),mutationBody=useRef(''),generation=useRef(0);
 const admin=user?.role==='admin'||user?.role==='super_admin';
 useEffect(()=>{api('/auth/csrf').then(d=>{csrf=d.csrf_token;return api('/auth/me')}).then(d=>setUser(d.user)).catch(()=>{}).finally(()=>setReady(true));},[]);
 async function refresh(){if(!user)return; const gen=++generation.current;setLoading(true);try{const [dash,ss,aa,ll]=await Promise.all([api('/dashboard'),api('/parking-slots'),api('/parking-areas'),api('/parking-locations')]);let result:Row={};const paths:Row={sessions:'/parking/sessions',payments:'/payments',vehicles:'/vehicles',rates:'/rates',staff:'/staff',audit:'/audit-logs',reports:`/reports/revenue?from=${from}&to=${to}`}; if(paths[page]) result=await api(paths[page]+(page==='reports'?'':`?page=${pageNum}${page==='sessions'?'&search='+encodeURIComponent(search):''}`));if(gen===generation.current){setDashboard(dash);setSlots(ss);setAreas(aa);setLocations(ll);setData(Array.isArray(result)?{rows:result}:result);setError('');}}catch(e){if(gen===generation.current)setError((e as Error).message)}finally{if(gen===generation.current)setLoading(false)}}
 useEffect(()=>{refresh();const timer=setInterval(refresh,15000);return()=>clearInterval(timer)},[user,page,pageNum,from,to,search]);
 useEffect(()=>{if(toast){const t=setTimeout(()=>setToast(''),5000);return()=>clearTimeout(t)}},[toast]);
 useEffect(()=>{if(!modal)return;const previous=document.activeElement as HTMLElement;const oldOverflow=document.body.style.overflow;document.body.style.overflow='hidden';const dialog=document.querySelector<HTMLElement>('[role=dialog]');const elements=()=>Array.from(dialog?.querySelectorAll<HTMLElement>('button:not([disabled]),input:not([type=hidden]),select,a[href]')||[]);const first=dialog?.querySelector<HTMLElement>('[autofocus]')||elements()[0];first?.focus();function keyboard(e:KeyboardEvent){if(e.key==='Escape'&&!busy)setModal('');if(e.key==='Tab'){const list=elements(),first=list[0],last=list[list.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}}}document.addEventListener('keydown',keyboard);return()=>{document.body.style.overflow=oldOverflow;document.removeEventListener('keydown',keyboard);previous?.focus()}},[modal,busy]);
 function go(p:string){setPage(p);setPageNum(1);setData({});setSearch('');setMobile(false);setError('')}
 function open(m:string){setModal(m);setError('');setQuote(null);setQuery('');setLost(false);setTicket(null);setEdit(null);mutationKey.current=crypto.randomUUID();mutationBody.current='';}
 async function perform(fn:()=>Promise<void>){setBusy(true);setError('');try{await fn()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 function values(e:FormEvent<HTMLFormElement>){e.preventDefault();return Object.fromEntries(new FormData(e.currentTarget)) as Row}
 function keyFor(body:Row){const serialized=JSON.stringify(body);if(mutationBody.current&&mutationBody.current!==serialized) mutationKey.current=crypto.randomUUID();mutationBody.current=serialized;return mutationKey.current}
 async function submitEntry(e:FormEvent<HTMLFormElement>){const v=values(e);await perform(async()=>{const s=await api('/parking/check-in','POST',v,keyFor(v));setTicket(s);setModal('ticket');setToast('Kendaraan masuk berhasil dicatat.');await refresh()})}
 async function findQuote(e:FormEvent<HTMLFormElement>){e.preventDefault();await perform(async()=>{let q=query.trim();if(q.includes('/ticket/'))q=q.split('/ticket/')[1].split(/[?#]/)[0];setQuote(await api('/parking/quote','POST',{query:q,lost_ticket:lost}));setQuery(q)})}
 async function checkout(e:FormEvent<HTMLFormElement>){const v=values(e);const body={query,lost_ticket:lost,vehicle_verified:v.vehicle_verified==='on',cash_received:Number(v.cash_received),expected_total:quote?.fee.total};await perform(async()=>{const d=await api('/parking/check-out','POST',body,keyFor(body));setTicket(d);setModal('receipt');setToast(d.message);await refresh()})}
 async function save(e:FormEvent<HTMLFormElement>,path:string){const v=values(e);await perform(async()=>{const d=await api(path,'POST',v);if(d.csrf_token)csrf=d.csrf_token;setModal('');setToast(d.message||'Data berhasil disimpan.');await refresh()})}
 const shownSlots=slots.filter(s=>(areaFilter==='all'||String(s.area_id)===areaFilter)&&(statusFilter==='all'||s.status===statusFilter)&&(!search||[s.code,s.license_plate].join(' ').toLowerCase().includes(search.toLowerCase())));
 const occupancy=dashboard.total_slots?Math.round(dashboard.occupied/dashboard.total_slots*100):0;
 function sessionTable(rows:Row[]){return rows?.length?<div className="table-wrap"><table><thead><tr><th>Kendaraan</th><th>Tiket & area</th><th>Waktu masuk</th><th>Slot</th><th>Status</th><th/></tr></thead><tbody>{rows.map(s=><tr key={s.id}><td><div className="vehicle-cell"><span className="vehicle-icon"><TypeIcon type={s.vehicle_type}/></span><div><strong>{s.license_plate}</strong><small>{types[s.vehicle_type]}</small></div></div></td><td><span className="mono">{s.ticket_number}</span><small>{s.area_name}</small></td><td>{date(s.entry_time)}</td><td><span className="slot-label">{s.slot_code}</span></td><td><Badge value={s.status}/></td><td><button className="icon-button" aria-label={'Lihat tiket '+s.ticket_number} onClick={()=>{setTicket(s);setModal('ticket')}}><ChevronRight size={18}/></button></td></tr>)}</tbody></table></div>:<Empty text="Belum ada kendaraan masuk."/>}
 if(!ready)return <div className="splash"><CircleParking size={48}/><span>Memuat ParkFlow…</span></div>;
 if(!user)return <div className="login-page"><section className="login-story"><div className="brand"><span className="brand-mark"><CircleParking/></span>parkflow<span className="brand-dot">.</span></div><span className="eyebrow">SMART PARKING MANAGEMENT</span><h1>Parkir teratur.<br/>Operasional<br/><em>lebih lancar.</em></h1><p>Satu tempat untuk mengelola kendaraan, ruang parkir, dan setiap transaksi.</p><div className="login-road"><div className="road-car"><Car size={60}/></div><i/><div className="road-car"><Car size={60}/></div><i/><div className="road-car highlighted"><CircleParking size={60}/></div></div><small>Dirancang untuk setiap perjalanan yang lebih baik.</small></section><section className="login-form"><div className="login-card"><span className="eyebrow">SELAMAT DATANG KEMBALI</span><h2>Masuk ke ParkFlow</h2><p>Kelola operasional parkir Anda hari ini.</p><form onSubmit={e=>{const v=values(e);perform(async()=>{const d=await api('/auth/login','POST',v);csrf=d.csrf_token;setUser(d.user)})}}><label>Email<input type="email" name="email" placeholder="nama@perusahaan.com" required autoComplete="username"/></label><label>Kata sandi<input type="password" name="password" placeholder="Masukkan kata sandi" required autoComplete="current-password"/></label>{error&&<div role="alert" className="error">{error}</div>}<button className="button primary full" disabled={busy}>{busy?<Loader2 className="spin" size={18}/>:<>Masuk ke dashboard <ArrowRight size={18}/></>}</button></form><div className="demo-note"><ShieldCheck size={19}/><div><strong>Akun demo lokal</strong><span>admin@parkflow.test / ParkFlow123!</span><span>Petugas: officer@parkflow.test</span></div></div></div><footer>ParkFlow © {new Date().getFullYear()} · Smart Parking Management</footer></section></div>;
 return <div className="app"><aside className={'sidebar '+(mobile?'mobile-open':'')}><a className="brand" href="#" onClick={e=>{e.preventDefault();go('dashboard')}}><span className="brand-mark"><CircleParking/></span>parkflow<span className="brand-dot">.</span></a><div className="workspace"><span className="workspace-icon"><MapPin size={19}/></span><div><strong>ParkFlow Central</strong><small>Workspace operasional</small></div><ChevronRight size={15}/></div><span className="nav-label">WORKSPACE</span><nav>{nav.filter(([id])=>admin||!adminPages.includes(id)).map(([id,label,Icon],i)=><button key={id} className={page===id?'nav-item selected':'nav-item'} onClick={()=>go(id)}><Icon size={19}/><span>{label}</span>{id==='sessions'&&dashboard.active_sessions>0&&<b>{dashboard.active_sessions}</b>}</button>)}</nav><div className="sidebar-bottom"><div className="system-status"><i/><div><strong>Sistem operasional</strong><small>Pembaruan setiap 15 detik</small></div></div><button className="profile" onClick={()=>go('settings')}><span className="avatar">{user.name.slice(0,1)}</span><div><strong>{user.name}</strong><small>{admin?'Administrator':'Parking Officer'}</small></div><Settings size={17}/></button></div></aside>{mobile&&<div className="sidebar-backdrop" onClick={()=>setMobile(false)}/>}
 <main className="main"><header className="topbar"><div className="breadcrumb"><button className="icon-button mobile-menu" onClick={()=>setMobile(!mobile)} aria-label="Buka menu"><Menu size={20}/></button><span>Workspace</span><ChevronRight size={14}/><strong>{nav.find(n=>n[0]===page)?.[1]}</strong></div><div className="top-actions"><span className="today">{new Date().toLocaleDateString('id-ID',{weekday:'short',day:'numeric',month:'long',year:'numeric'})}</span><button className="icon-button" aria-label="Pemberitahuan" onClick={()=>setNotifications(!notifications)}><Bell size={19}/>{dashboard.available<10&&<i className="notification-dot"/>}</button><span className="avatar small">{user.name.slice(0,1)}</span></div>{notifications&&<div className="notification-panel"><strong>Pemberitahuan kapasitas</strong><p>{dashboard.available<10?'Kapasitas hampir penuh. Pantau alokasi kendaraan.':'Kapasitas parkir masih tersedia.'}</p><span>{dashboard.available} slot tersedia dari {dashboard.total_slots} slot.</span></div>}</header>
 <div className="content"><div className="page-heading"><div><div className="eyebrow">PARKING OPERATIONS</div><h1>{page==='dashboard'?'Ringkasan operasional':nav.find(n=>n[0]===page)?.[1]}</h1><p>{({dashboard:'Pantau aktivitas parkir dan kelola operasional dalam satu tempat.',slots:'Lihat ketersediaan ruang parkir di setiap area.',sessions:'Semua perjalanan kendaraan, dari masuk hingga keluar.',payments:'Catatan pembayaran tunai yang tersimpan dengan aman.',vehicles:'Daftar kendaraan yang pernah menggunakan area parkir.',reports:'Tinjau pendapatan dan kinerja operasional Anda.',locations:'Kelola lokasi serta area operasional parkir.',rates:'Atur tarif per jenis kendaraan dengan perhitungan otomatis.',staff:'Akun dan hak akses tim operasional.',audit:'Jejak aktivitas sistem yang tercatat secara otomatis.',settings:'Kelola keamanan akun Anda.'} as Row)[page]}</p></div><div className="heading-actions"><button className="button secondary" onClick={()=>open('exit')}><ArrowUpRight size={17}/>Check-out</button><button className="button primary" onClick={()=>open('entry')}><Plus size={18}/>Check-in kendaraan</button></div></div>
 {error&&!modal&&<div className="error" role="alert">{error}<button onClick={refresh}>Coba lagi</button></div>}
 {page==='dashboard'&&<><div className="welcome-strip"><div><span className="live"><i/>LIVE OVERVIEW</span><strong>Selamat {new Date().getHours()<11?'pagi':new Date().getHours()<15?'siang':new Date().getHours()<18?'sore':'malam'}, {user.name.split(' ')[0]} 👋</strong><p>{dashboard.active_sessions||0} kendaraan sedang parkir. Semuanya dalam pantauan Anda.</p></div><div className="welcome-visual"><div className="parking-p">P</div><Car size={66}/><div className="visual-line"/></div></div>
 <div className="stats-grid">{[[Grid2X2,'Slot tersedia',dashboard.available||0,`dari ${dashboard.total_slots||0} total slot`,'mint'],[Car,'Kendaraan hari ini',dashboard.vehicles_today||0,'Tercatat sejak pukul 00.00','blue'],[Wallet,'Pendapatan hari ini',money(dashboard.revenue_today),'Pembayaran tunai terkonfirmasi','amber'],[BarChart3,'Tingkat okupansi',occupancy+'%',`${dashboard.occupied||0} slot sedang terisi`,'violet']].map(([Icon,label,value,sub,color]:any)=><section className="stat-card" key={label}><div className="stat-top"><span>{label}</span><span className={'stat-icon '+color}><Icon size={20}/></span></div><strong>{value}</strong><small>{sub}</small></section>)}</div>
 <div className="dashboard-middle"><section className="panel revenue-panel"><div className="panel-heading"><div><h2>Tren pendapatan</h2><p>Aktivitas pembayaran 7 hari terakhir</p></div><span className="chip">7 hari terakhir</span></div><div className="chart-total">{money((dashboard.trend||[]).reduce((sum:number,d:Row)=>sum+d.revenue,0))}<span>Total pendapatan</span></div><div className="chart"><div className="chart-grid"><span>{money(Math.max(10000,...(dashboard.trend||[]).map((x:Row)=>x.revenue)))}</span><span>{money(Math.max(10000,...(dashboard.trend||[]).map((x:Row)=>x.revenue))/2)}</span><span>Rp 0</span></div><div className="bars">{(dashboard.trend||[]).map((d:Row)=><div className="bar-column" key={d.date}><div className="bar-track"><div className="bar" style={{height:Math.max(2,d.revenue/Math.max(10000,...dashboard.trend.map((x:Row)=>x.revenue))*100)+'%'}} title={money(d.revenue)}/></div><span>{new Date(d.date+'T12:00:00').toLocaleDateString('id-ID',{weekday:'short'})}</span></div>)}</div></div><div className="chart-legend"><i/>Pendapatan parkir <span>· Rupiah (IDR)</span></div></section><section className="panel occupancy-panel"><div className="panel-heading"><div><h2>Kapasitas parkir</h2><p>Ketersediaan seluruh area</p></div><Grid2X2 size={18}/></div><div className="donut" style={{background:`conic-gradient(#159b7d 0 ${occupancy}%, #edf3f0 ${occupancy}% 100%)`}}><div><strong>{occupancy}<em>%</em></strong><span>Terisi saat ini</span></div></div><div className="capacity-legend"><div><i className="dot green"/>Terisi<strong>{dashboard.occupied||0}</strong></div><div><i className="dot light"/>Tersedia<strong>{dashboard.available||0}</strong></div><div><i className="dot gray"/>Nonaktif / perawatan<strong>{(dashboard.total_slots||0)-(dashboard.available||0)-(dashboard.occupied||0)}</strong></div></div></section></div>
 <section className="panel"><div className="panel-heading"><div><h2>Aktivitas parkir terbaru</h2><p>Kendaraan terakhir yang tercatat di sistem</p></div><button className="text-button" onClick={()=>go('sessions')}>Lihat semua <ArrowRight size={16}/></button></div>{sessionTable(dashboard.recent)}</section><div className="area-overview"><div className="section-title"><h2>Area parkir</h2><button className="text-button" onClick={()=>go('slots')}>Kelola area <ArrowRight size={16}/></button></div><div className="area-cards">{areas.map(a=>{const ss=slots.filter(s=>s.area_id===a.id),occupied=ss.filter(s=>s.status==='OCCUPIED').length,available=ss.filter(s=>s.status==='AVAILABLE').length;return <button key={a.id} className="area-card" onClick={()=>{setAreaFilter(String(a.id));go('slots')}}><div><span className="vehicle-icon"><TypeIcon type={a.vehicle_type}/></span><Badge value={available?'AVAILABLE':'OCCUPIED'}/></div><h3>{a.name}</h3><p>{available} tersedia <span>/ {ss.length} slot</span></p><div className="progress"><i style={{width:(ss.length?occupied/ss.length*100:0)+'%'}}/></div></button>})}</div></div></>}
 {page==='slots'&&<><div className="filters"><div className="search-box"><Search size={17}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Cari slot atau plat kendaraan…" aria-label="Cari slot"/></div><select aria-label="Filter area" value={areaFilter} onChange={e=>setAreaFilter(e.target.value)}><option value="all">Semua area</option>{areas.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select><select aria-label="Filter status" value={statusFilter} onChange={e=>setStatusFilter(e.target.value)}><option value="all">Semua status</option>{['AVAILABLE','OCCUPIED','MAINTENANCE','DISABLED'].map(s=><option key={s} value={s}>{statuses[s]}</option>)}</select>{admin&&<button className="button primary" onClick={()=>open('area')}><Plus size={16}/>Tambah area</button>}</div><section className="panel"><div className="panel-heading"><div><h2>Peta slot parkir</h2><p>{shownSlots.length} slot sesuai filter · Klik slot untuk melihat detail</p></div><span className="live"><i/>LIVE</span></div><div className="slot-grid">{shownSlots.map(s=><button key={s.id} className={'parking-slot '+s.status.toLowerCase()} onClick={()=>{setEdit(s);setModal('slot');setError('')}}><TypeIcon type={s.vehicle_type} size={30}/><strong>{s.code}</strong><small>{s.license_plate||statuses[s.status]}</small></button>)}</div>{!shownSlots.length&&<Empty text="Tidak ada slot sesuai filter."/>}<div className="slot-legend">{['AVAILABLE','OCCUPIED','MAINTENANCE','DISABLED'].map(s=><Badge key={s} value={s}/>)}</div></section></>}
 {page==='sessions'&&<section className="panel"><div className="panel-heading"><h2>Riwayat sesi parkir</h2><div className="search-box"><Search size={17}/><input placeholder="Cari plat, tiket, atau slot…" aria-label="Cari sesi" value={search} onChange={e=>{setSearch(e.target.value);setPageNum(1)}}/></div></div>{sessionTable(data.data)}</section>}
 {page==='payments'&&<section className="panel"><div className="panel-heading"><div><h2>Semua transaksi</h2><p>Pembayaran tunai yang telah diselesaikan</p></div><Badge value="PAID"/></div>{data.data?.length?<div className="table-wrap"><table><thead><tr><th>Referensi</th><th>Kendaraan</th><th>Waktu</th><th>Petugas</th><th>Total</th><th>Status</th></tr></thead><tbody>{data.data.map((p:Row)=><tr key={p.id}><td className="mono">{p.reference}</td><td><strong>{p.license_plate}</strong><small>{p.ticket_number}</small></td><td>{date(p.created_at)}</td><td>{p.officer_name}</td><td><strong>{money(p.amount)}</strong></td><td><Badge value={p.status}/></td></tr>)}</tbody></table></div>:<Empty text="Belum ada pembayaran."/>}</section>}
 {page==='vehicles'&&<section className="panel"><div className="panel-heading"><h2>Daftar kendaraan</h2><span className="chip">{data.total||0} kendaraan</span></div>{data.data?.length?<div className="table-wrap"><table><thead><tr><th>Plat kendaraan</th><th>Jenis</th><th>Pertama terdaftar</th></tr></thead><tbody>{data.data.map((v:Row)=><tr key={v.id}><td><strong>{v.license_plate}</strong></td><td>{types[v.vehicle_type]}</td><td>{date(v.created_at)}</td></tr>)}</tbody></table></div>:<Empty/>}</section>}
 {page==='reports'&&<><div className="filters"><label className="inline-label">Dari<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label className="inline-label">Sampai<input type="date" value={to} min={from} onChange={e=>setTo(e.target.value)}/></label><a className="button primary" href={`/api/reports/revenue?from=${from}&to=${to}&format=csv`}><Download size={17}/>Ekspor CSV</a><button className="button secondary" onClick={()=>window.print()}><Printer size={17}/>Cetak / PDF</button></div><div className="stats-grid report-stats"><div className="stat-card"><span>Total pendapatan</span><strong>{money(data.total_revenue)}</strong></div><div className="stat-card"><span>Transaksi selesai</span><strong>{data.total_transactions||0}</strong></div><div className="stat-card"><span>Rata-rata durasi</span><strong>{data.average_duration||0} <small>menit</small></strong></div></div><section className="panel"><div className="panel-heading"><h2>Laporan pendapatan</h2><span>{from} — {to}</span></div>{data.rows?.length?<div className="table-wrap"><table><thead><tr><th>Transaksi</th><th>Plat</th><th>Keluar</th><th>Durasi</th><th>Petugas</th><th>Pendapatan</th></tr></thead><tbody>{data.rows.map((r:Row)=><tr key={r.reference}><td>{r.reference}</td><td>{r.license_plate}</td><td>{date(r.exit_time)}</td><td>{r.duration_minutes} menit</td><td>{r.officer}</td><td>{money(r.amount)}</td></tr>)}</tbody></table></div>:<Empty text="Belum ada transaksi pada periode ini."/>}</section></>}
 {page==='locations'&&<><div className="filters"><button className="button primary" onClick={()=>open('location')}><Plus size={17}/>Tambah lokasi</button><button className="button secondary" onClick={()=>open('area')}><Plus size={17}/>Tambah area & slot</button></div><div className="location-cards">{locations.map(l=><section className="panel location-card" key={l.id}><span className="stat-icon mint"><MapPin size={23}/></span><h2>{l.name}</h2><p>{l.address}</p><div className="location-areas">{areas.filter(a=>a.location_id===l.id).map(a=><div key={a.id}><span><TypeIcon type={a.vehicle_type}/>{a.name}</span><b>{slots.filter(s=>s.area_id===a.id).length} slot</b></div>)}</div></section>)}</div></>}
 {page==='rates'&&<><div className="info-banner"><ShieldCheck size={21}/><span>Tarif disimpan saat check-in. Perubahan tarif hanya berlaku untuk kendaraan yang masuk setelahnya. Batas tarif dihitung per blok 24 jam.</span></div><div className="rate-grid">{data.rows?.map((r:Row)=><section key={r.id} className="panel rate-card"><div className="rate-title"><span className="vehicle-icon"><TypeIcon type={r.vehicle_type}/></span><h2>{types[r.vehicle_type]}</h2></div><strong className="rate-price">{money(r.first_hour)}<small> / jam pertama</small></strong><dl><div><dt>Jam berikutnya</dt><dd>{money(r.additional_hour)}</dd></div><div><dt>Maksimal / 24 jam</dt><dd>{money(r.daily_max)}</dd></div><div><dt>Denda tiket hilang</dt><dd>{money(r.lost_penalty)}</dd></div></dl><button className="button secondary full" onClick={()=>{setEdit(r);setModal('rate');setError('')}}><SlidersHorizontal size={16}/>Ubah tarif</button></section>)}</div></>}
 {page==='staff'&&<section className="panel"><div className="panel-heading"><div><h2>Tim operasional</h2><p>Akun demo dikelola melalui database seeder.</p></div></div><div className="table-wrap"><table><thead><tr><th>Nama</th><th>Email</th><th>Hak akses</th></tr></thead><tbody>{data.rows?.map((u:Row)=><tr key={u.id}><td><strong>{u.name}</strong></td><td>{u.email}</td><td><span className="chip">{u.role==='admin'?'Administrator':'Parking Officer'}</span></td></tr>)}</tbody></table></div></section>}
 {page==='audit'&&<section className="panel"><div className="panel-heading"><div><h2>Jejak audit</h2><p>Catatan aktivitas hanya dapat dibaca.</p></div><ShieldCheck size={21}/></div>{data.data?.length?<div className="table-wrap"><table><thead><tr><th>Waktu</th><th>Aktivitas</th><th>Subjek</th><th>Pengguna</th></tr></thead><tbody>{data.data.map((r:Row)=><tr key={r.id}><td>{date(r.created_at)}</td><td><span className="chip">{r.action}</span></td><td>{r.subject}</td><td>{r.user_name}</td></tr>)}</tbody></table></div>:<Empty/>}</section>}
 {page==='settings'&&<section className="panel settings-panel"><h2>Keamanan akun</h2><p>{user.name} · {user.email}</p><form onSubmit={e=>save(e,'/auth/password')}><label>Kata sandi saat ini<input type="password" name="current_password" required autoComplete="current-password"/></label><label>Kata sandi baru<input type="password" name="password" minLength={12} required autoComplete="new-password"/><small>Minimal 12 karakter.</small></label><label>Konfirmasi kata sandi<input type="password" name="password_confirmation" minLength={12} required autoComplete="new-password"/></label><button className="button primary" disabled={busy}>Simpan kata sandi</button></form><hr/><button className="button danger" onClick={()=>perform(async()=>{await api('/auth/logout','POST');setUser(null);go('dashboard');const d=await api('/auth/csrf');csrf=d.csrf_token})}><LogOut size={17}/>Keluar dari akun</button></section>}
 {data.last_page>1&&<div className="pagination"><button className="button secondary" disabled={pageNum===1} onClick={()=>setPageNum(pageNum-1)}>Sebelumnya</button><span>Halaman {pageNum} dari {data.last_page}</span><button className="button secondary" disabled={pageNum>=data.last_page} onClick={()=>setPageNum(pageNum+1)}>Berikutnya</button></div>}
 <footer className="page-footer"><span>ParkFlow <b>·</b> Smart Parking Management</span><button className="text-button" onClick={refresh}><RefreshCw size={13} className={loading?'spin':''}/>{loading?'Memperbarui…':'Perbarui data'}</button></footer></div></main>
 {toast&&<div className="toast" role="status"><Check size={20}/>{toast}</div>}
 {modal&&<div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget&&!busy)setModal('')}}><section className={'modal '+(['ticket','receipt'].includes(modal)?'ticket-modal':'')} role="dialog" aria-modal="true" aria-label="Operasional parkir"><div className="modal-header"><div><span className="eyebrow">PARKFLOW</span><h2>{({entry:'Check-in kendaraan',exit:'Check-out & pembayaran',ticket:'Tiket parkir digital',receipt:'Pembayaran berhasil',area:'Tambah area parkir',location:'Tambah lokasi',rate:'Ubah tarif parkir',slot:'Detail slot'} as Row)[modal]}</h2></div><button className="icon-button" onClick={()=>setModal('')} disabled={busy} aria-label="Tutup dialog"><X size={21}/></button></div>{error&&<div role="alert" className="error">{error}</div>}
 {modal==='entry'&&<form onSubmit={submitEntry}><div className="info-banner"><Ticket size={20}/><span>Slot tersedia dipilih otomatis. Tiket QR dibuat setelah check-in.</span></div><label>Nomor plat kendaraan<input name="license_plate" placeholder="B 1234 ABC" required maxLength={15} autoFocus className="plate-input"/></label><label>Jenis kendaraan<select name="vehicle_type" value={type} onChange={e=>setType(e.target.value)}>{Object.entries(types).map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label><label>Area parkir<select key={type} name="area_id" required defaultValue=""><option value="" disabled>Pilih area yang tersedia</option>{areas.filter(a=>a.vehicle_type===type).map(a=>{const n=slots.filter(s=>s.area_id===a.id&&s.status==='AVAILABLE').length;return <option key={a.id} value={a.id} disabled={!n}>{a.name} — {n} slot tersedia</option>})}</select></label><button className="button primary full" disabled={busy}>{busy?<Loader2 className="spin" size={18}/>:<ArrowDownLeft size={18}/>}Buat tiket & check-in</button></form>}
 {modal==='exit'&&<><form onSubmit={findQuote}><label>Nomor tiket, plat, atau hasil scan QR<div className="input-icon"><ScanLine size={20}/><input placeholder="PF-… / B 1234 ABC / URL tiket" value={query} onChange={e=>{setQuery(e.target.value);setQuote(null)}} required autoFocus/></div></label><label className="checkbox"><input type="checkbox" checked={lost} onChange={e=>{setLost(e.target.checked);setQuote(null)}}/>Tiket hilang — terapkan denda</label><button className="button secondary full" disabled={busy}><Search size={17}/>Cari & hitung tagihan</button></form>{quote&&<form onSubmit={checkout} className="checkout-form"><div className="checkout-vehicle"><TypeIcon type={quote.session.vehicle_type} size={30}/><div><strong>{quote.session.license_plate}</strong><small>{quote.session.slot_code} · {date(quote.session.entry_time)}</small></div></div><dl className="bill"><div><dt>Durasi parkir</dt><dd>{quote.fee.duration_minutes} menit ({quote.fee.billable_hours} jam tagihan)</dd></div><div><dt>Tarif parkir</dt><dd>{money(quote.fee.subtotal)}</dd></div><div><dt>Denda tiket hilang</dt><dd>{money(quote.fee.penalty)}</dd></div><div className="bill-total"><dt>Total pembayaran</dt><dd>{money(quote.fee.total)}</dd></div></dl><label>Uang tunai diterima (Rp)<input name="cash_received" type="number" required min={quote.fee.total} max={100000000} defaultValue={quote.fee.total}/></label><label className="checkbox"><input name="vehicle_verified" type="checkbox" required/>Saya sudah memverifikasi plat dan kendaraan.</label><button className="button primary full" disabled={busy}><Wallet size={18}/>Bayar tunai & check-out</button></form>}</>}
 {modal==='ticket'&&ticket&&<div className="ticket-body"><span className="brand ticket-brand"><CircleParking/>parkflow.</span><Badge value={ticket.status}/><h3>{ticket.license_plate}</h3><p>{ticket.ticket_number}</p><QR token={ticket.ticket_token}/><dl><div><dt>Lokasi</dt><dd>{ticket.location_name}</dd></div><div><dt>Area / slot</dt><dd>{ticket.area_name} / {ticket.slot_code}</dd></div><div><dt>Waktu masuk</dt><dd>{date(ticket.entry_time)}</dd></div></dl><p className="ticket-note">Simpan tiket ini dan tunjukkan kepada petugas saat keluar.</p><button className="button primary full no-print" onClick={()=>window.print()}><Printer size={17}/>Cetak tiket</button></div>}
 {modal==='receipt'&&ticket&&<div className="ticket-body"><span className="success-circle"><Check size={32}/></span><h3>{money(ticket.total)}</h3><p>{ticket.reference}</p><dl><div><dt>Kendaraan</dt><dd>{ticket.session.license_plate}</dd></div><div><dt>Kembalian</dt><dd>{money(ticket.change)}</dd></div><div><dt>Status</dt><dd>Lunas · Slot tersedia kembali</dd></div></dl><button className="button primary full no-print" onClick={()=>window.print()}><Printer size={17}/>Cetak struk</button></div>}
 {modal==='location'&&<form onSubmit={e=>save(e,'/parking-locations')}><label>Nama lokasi<input name="name" required maxLength={100}/></label><label>Alamat<input name="address" required maxLength={255}/></label><button className="button primary full" disabled={busy}>Simpan lokasi</button></form>}
 {modal==='area'&&<form onSubmit={e=>save(e,'/parking-areas')}><label>Lokasi<select name="location_id" required>{locations.map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select></label><label>Nama area<input name="name" placeholder="Basement 3" required maxLength={100}/></label><label>Jenis kendaraan<select name="vehicle_type">{Object.entries(types).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><div className="form-row"><label>Prefix slot<input name="prefix" placeholder="B3" pattern="[A-Z0-9-]{1,12}" required maxLength={12}/></label><label>Jumlah slot<input type="number" name="capacity" min={1} max={500} defaultValue={20} required/></label></div><button className="button primary full" disabled={busy}>Buat area & slot</button></form>}
 {modal==='rate'&&edit&&<form onSubmit={e=>save(e,'/rates')}><input name="vehicle_type" type="hidden" value={edit.vehicle_type}/><h3>{types[edit.vehicle_type]}</h3>{[['first_hour','Jam pertama'],['additional_hour','Jam berikutnya'],['daily_max','Maksimal per 24 jam'],['lost_penalty','Denda tiket hilang']].map(([key,label])=><label key={key}>{label} (Rp)<input type="number" name={key} defaultValue={edit[key]} min={key==='daily_max'?1:0} max={10000000} required/></label>)}<button className="button primary full" disabled={busy}>Simpan tarif</button></form>}
 {modal==='slot'&&edit&&<div><div className="slot-detail"><TypeIcon type={edit.vehicle_type} size={48}/><h3>{edit.code}</h3><Badge value={edit.status}/><p>{edit.area_name} · {types[edit.vehicle_type]}</p>{edit.license_plate&&<><strong>{edit.license_plate}</strong><p>Masuk {date(edit.entry_time)}</p></>}</div>{admin&&edit.status!=='OCCUPIED'&&<form onSubmit={e=>{const v=values(e);perform(async()=>{await api('/parking-slots/'+edit.id,'PATCH',v);setModal('');setToast('Status slot diperbarui.');await refresh()})}}><label>Status slot<select name="status" defaultValue={edit.status}>{['AVAILABLE','MAINTENANCE','DISABLED'].map(s=><option key={s} value={s}>{statuses[s]}</option>)}</select></label><button className="button primary full" disabled={busy}>Simpan status</button></form>}</div>}
 </section></div>}</div>
}
