const {chromium}=require('@playwright/test');
(async()=>{
 const browser=await chromium.launch({...(process.env.CHROME_PATH?{executablePath:process.env.CHROME_PATH}:process.platform==='darwin'?{executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'}:{}),headless:true});
 const page=await browser.newPage({viewport:{width:1440,height:1100}});page.setDefaultTimeout(15000);const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('http://127.0.0.1:3000');await page.getByLabel('Email',{exact:true}).fill('admin@parkflow.test');await page.getByLabel('Kata sandi',{exact:true}).fill('ParkFlow123!');await page.getByRole('button',{name:'Masuk ke dashboard'}).click();await page.getByRole('heading',{name:'Ringkasan operasional'}).waitFor();
 await page.waitForTimeout(700);await page.screenshot({path:'../docs/dashboard.png',fullPage:true});
 await page.getByRole('button',{name:'Check-in kendaraan',exact:true}).click();const plate='B '+Math.floor(1000+Math.random()*9000)+' E2E';await page.getByLabel('Nomor plat kendaraan').fill(plate);await page.locator('select[name=area_id]').selectOption('1');await page.getByRole('button',{name:'Buat tiket & check-in'}).click();await page.getByRole('heading',{name:'Tiket parkir digital'}).waitFor();await page.getByAltText('QR tiket parkir').waitFor();await page.screenshot({path:'../docs/ticket.png'});
 await page.getByRole('button',{name:'Tutup dialog'}).click();await page.getByRole('button',{name:'Check-out',exact:true}).click();await page.getByLabel('Nomor tiket, plat, atau hasil scan QR').fill(plate);await page.getByRole('button',{name:'Cari & hitung tagihan'}).click();await page.getByLabel('Uang tunai diterima (Rp)').fill('10000');await page.getByLabel('Saya sudah memverifikasi plat dan kendaraan.').check();await page.getByRole('button',{name:'Bayar tunai & check-out'}).click();await page.getByRole('heading',{name:'Pembayaran berhasil'}).waitFor();await page.getByRole('button',{name:'Tutup dialog'}).click();
 for(const label of ['Area & slot','Sesi parkir','Transaksi','Kendaraan','Laporan','Lokasi','Tarif parkir','Petugas','Audit aktivitas','Pengaturan']){await page.getByRole('button',{name:label,exact:true}).click();await page.getByRole('heading',{name:label,exact:true}).waitFor();await page.waitForTimeout(200);if(await page.locator('.content>.error').count())throw Error(label+': '+await page.locator('.content>.error').textContent());}
 await page.getByRole('button',{name:'Ringkasan',exact:true}).click();await page.setViewportSize({width:390,height:844});await page.waitForTimeout(5200);await page.screenshot({path:'../docs/mobile.png',fullPage:true});const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);if(overflow)throw Error('Mobile horizontal overflow');
 const rejected=await page.request.post('http://127.0.0.1:3000/api/rates',{data:{}});if(rejected.status()!==419)throw Error('CSRF missing token should be rejected');if(errors.length)throw Error(errors.join('\n'));console.log(JSON.stringify({result:'passed',checks:['admin login','dashboard','QR ticket','cash checkout','10 navigation pages','390px responsive layout','no browser errors'],plate}));await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
